name: 'Setup Node.js Environment'
description: 'Setup Node.js and installs dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'
  cache:
    description: 'Enable caching of node modules'
    required: false
    default: 'npm'
  
runs
  using: 'composite'
  steps:
    - name: Validate cache input
      shell: bash
      run: |
        if [[ "${{ inputs.cache }}" != "npm" && "${{ inputs.cache }}" != "yarn" ]]; then
          echo "Error: cache must be either 'npm' or 'yarn'."
          exit 1
        fi
    - name: Setup Node.js
      uses: actions/setup-node@4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
    
    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ inputs.clean-install }}" == "npm" ]]; then
          rm -rf node_modules package-lock.json
          npm install